# Generated by Django 5.1.1 on 2024-10-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca'),
            preserve_default=False,
        ),
    ]
